server:
  port: 1990
  servlet:
    context-path: /day

rocketmq:
  name-server: 60.204.238.17:9876
  # 生产者
  producer:
    group: my-group
    # 消息发送超时时间
    send-message-timeout: 3000
    # 消息最大长度4M
    max-message-size: 4096
    # 消息发送失败重试次数
    retry-times-when-send-failed: 3
    # 异步消息发送失败重试次数
    retry-times-when-send-async-failed: 2